### ISSUE TITLE
ENOENT: no such file or directory, open '/usr/src/conduit-wasm/pkg/conduit_wasm_bg.js'

### ISSUE THREAD

**Issue by istx25** [jetli/rust-yew-realworld-example-app#13]
**Describe the bug**
When I run `docker-compose up` I get the following error:

```
conduit-wasm_1  | Server running at http://localhost:8000 
conduit-wasm_1  | ?  /usr/src/conduit-wasm/Cargo.toml: ENOENT: no such file or directory, open '/usr/src/conduit-wasm/pkg/conduit_wasm_bg.js'
conduit-wasm_1  | Error: ENOENT: no such file or directory, open '/usr/src/conduit-wasm/pkg/conduit_wasm_bg.js'
conduit-wasm_1  | Unexpected error while opening in browser: true
conduit-wasm_1  | Error: Exited with code 3
conduit-wasm_1  |     at ChildProcess.<anonymous> (/usr/src/conduit-wasm/node_modules/opn/index.js:85:13)
conduit-wasm_1  |     at Object.onceWrapper (events.js:422:26)
conduit-wasm_1  |     at ChildProcess.emit (events.js:315:20)
conduit-wasm_1  |     at maybeClose (internal/child_process.js:1021:16)
conduit-wasm_1  |     at Socket.<anonymous> (internal/child_process.js:443:11)
conduit-wasm_1  |     at Socket.emit (events.js:315:20)
conduit-wasm_1  |     at Pipe.<anonymous> (net.js:674:12)
```

**Expected behavior**
It should build and show up on the webpage.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: FireFox
 - Version: Master

**Comment by EvanCarroll** [comment]
Getting the same thing,

```
Server running at http://localhost:8000 
🚨  /tmp/rust-yew-realworld-example-app/crates/conduit-wasm/Cargo.toml: ENOENT: no such file or directory, open '/tmp/rust-yew-realworld-example-app/crates/conduit-wasm/pkg/conduit_wasm_bg.js'
Error: ENOENT: no such file or directory, open '/tmp/rust-yew-realworld-example-app/crates/conduit-wasm/pkg/conduit_wasm_bg.js'
```

**Comment by cesmejia** [comment]
Same here! Any update on this one?

**Comment by istx25** [comment]
Thanks, #14 fixed it for me.

**Comment by EvanCarroll** [comment]
Very excited to give this a shot! Thanks a ton Yew devs.
