### ISSUE TITLE
Can't run in Windows 11

### ISSUE THREAD

**Issue by nanqic** [jetli/rust-yew-realworld-example-app#41]
**Describe the bug**
I following the guide, start the app, but got error.

**To Reproduce**
1. npm start
``` 
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> start
> cd crates/conduit-wasm && npm start

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> conduit-wasm@0.1.0 start
> cross-env WASM_PACK_PROFILE=dev parcel static/index.html -p 8000 --open

Server running at http://localhost:8000 
√  Built in 482ms.
```
2. Open Chrome, got white page, the console output
```
 Uncaught TypeError: Cannot read properties of undefined (reading 'memory')
    at parcelRequire.../node_modules/parcel-plugin-wasm.rs/wasm-loader.js.fs (wasm-loader.js:913:1)
    at newRequire (static.77de5100.js:47:24)
    at localRequire (static.77de5100.js:53:14)
    at parcelRequire.0 (wasm-loader.js:958:1)
    at newRequire (static.77de5100.js:47:24)
    at static.77de5100.js:81:7
    at static.77de5100.js:120:3
```
3. I also tried run tauri version, but still have problem.
```
cargo tauri dev
     Running BeforeDevCommand (`npm start`)
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> start
> cd crates/conduit-wasm && npm start

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> conduit-wasm@0.1.0 start
> cross-env WASM_PACK_PROFILE=dev parcel static/index.html -p 8000 --open

Server running at http://localhost:8000 
√  Built in 511ms.
   Compiling webview2-com v0.16.0
   Compiling conduit-tauri v0.1.0 (D:\ideaProjects\world_hello\rust-yew-realworld-example-app\crates\conduit-tauri)
error: failed to run custom build command for `conduit-tauri v0.1.0 (D:\ideaProjects\world_hello\rust-yew-realworld-example-app\crates\conduit-tauri)`

Caused by:
  process didn't exit successfully: `D:\ideaProjects\world_hello\rust-yew-realworld-example-app\target\debug\build\conduit-tauri-7686d36fb79bdf2b\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=dev
  package.metadata does not exist
warning: build failed, waiting for other jobs to finish...
```

**Desktop (please complete the following information):**
 - OS: [Windows 11
 - Browser [hrome]
 - Version [ 103.0.5060.53]

**Additional context**
I am a beginer for rust, would you help me to run this app?

**Comment by jetli** [comment]
updated the repo, force to use wasm-bindgen = "=0.2.80" for now, please update and try again.

**Comment by nanqic** [comment]
It works, thank you very much!
